name: "Release Workflow"

on:
  push:
    tags:
      - "*"

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: 3.8

      # https://github.com/tom-mi/python-mkp/
      - name: Install Dependencies
        run: |
          python -m pip install --upgrade pip
          pip install mkp

      - name: Run Script
        run: |
          python ./dist.py

      - name: Create Release
        id: create_release
        uses: ncipollo/release-action@v1
        with:
          artifacts: "dist/*.mkp"
          token: ${{ secrets.GITHUB_TOKEN }}
